# Generated by Django 5.2 on 2025-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriap',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='categoriap',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriap',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
